---
abstract: 'autobox methods for (de)camelcasing'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autobox-Camelize
no_index:
  directory:
    - corpus
    - t
provides:
  autobox::Camelize:
    file: lib/autobox/Camelize.pm
    version: 0.001
  autobox::Camelize::STRING:
    file: lib/autobox/Camelize.pm
    version: 0.001
requires:
  autobox: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/RsrchBoy/autobox-Camelize/issues
  repository: git://github.com/RsrchBoy/autobox-Camelize.git
version: 0.001
x_Dist_Zilla:
  perl:
    version: 5.016002
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RSRCHBOY/NextRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RSRCHBOY/Git::NextVersion'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@RSRCHBOY/ContributorsFromGit'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::Fixups'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::MergeConflicts'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RSRCHBOY/GatherDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RSRCHBOY/PruneCruft'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RSRCHBOY/ExecDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RSRCHBOY/ShareDir'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@RSRCHBOY/MakeMaker'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@RSRCHBOY/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RSRCHBOY/Manifest'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@RSRCHBOY/SurgicalPkgVersion'
      version: 0.0019
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@RSRCHBOY/ReadmeFromPod'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@RSRCHBOY/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@RSRCHBOY/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RSRCHBOY/AutoPrereqs'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@RSRCHBOY/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@RSRCHBOY/Test::PodSpelling'
      version: 2.004003
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@RSRCHBOY/ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@RSRCHBOY/PodCoverageTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RSRCHBOY/PodSyntaxTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@RSRCHBOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@RSRCHBOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@RSRCHBOY/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@RSRCHBOY/Test::Compile'
      version: 2.001
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@RSRCHBOY/ExtraTests'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::NoSmartCommentsTests
      name: '@RSRCHBOY/NoSmartCommentsTests'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@RSRCHBOY/Test::Pod::LinkCheck'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RSRCHBOY/MetaConfig'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RSRCHBOY/MetaJSON'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RSRCHBOY/MetaYAML'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@RSRCHBOY/MetaNoIndex'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@RSRCHBOY/MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@RSRCHBOY/GitHub::Meta'
      version: 0.31
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RSRCHBOY/TestRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@RSRCHBOY/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RSRCHBOY/CheckPrereqsIndexed'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RSRCHBOY/Git::Check'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RSRCHBOY/ConfirmRelease'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RSRCHBOY/Git::Commit'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RSRCHBOY/Git::Tag'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@RSRCHBOY/Git::CommitBuild'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RSRCHBOY/UploadToCPAN'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RSRCHBOY/Git::Push'
      version: 2.009
    -
      class: Dist::Zilla::Plugin::Signature
      name: '@RSRCHBOY/Signature'
      version: 1.100930
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@RSRCHBOY/Twitter'
      version: 0.020
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@RSRCHBOY/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@RSRCHBOY/GitHub::Update'
      version: 0.31
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@RSRCHBOY/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::License
      name: '@RSRCHBOY/License'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@RSRCHBOY/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@RSRCHBOY/ReadmePodInRoot'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@RSRCHBOY/CPANFile'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@RSRCHBOY/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: Test::Synopsis
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300030
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300030
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300030
